#hashtag lists to crawl
HASHTAGS = ["photography", "streetphotography", "photo", "photos", 
            "NaturePhotography", "HappyMonday", "HappyTuesday", "HappyWednesday", 
            "HappyThursday", "HappyFriday", "HappySaturday","HappySunday", 
            "naturalbeauty", "house", "nature", "sunsets", "sunrise", "reflection",
            "landscape", "design", "architecture", "mountains", "Fuji", "winter",
            "spring", "summer", "fall", "shotoniphone", "morning", "tree", "wildlife",
            "camera", "カメラ", "いいね" , "フォロー" , "配信" , "RT" , "retweet" , "車好き" , 
            "車" , "中古車" , "今日のコーデ" , "韓国ファッション" , "韓国通販" , 
            "ヤフオク" , "春" , "成人式" , "同窓会" , "ファッション" , "地雷系女子" ,
            "港区女子" , "癒し" , "かわいい" , "一人暮らし" , "散歩" , "日の出" , "歴史" ,
            "小説" , "バイク" ,"ヤンキー" , "リス" , "あるある" , "芸能人" , "ガッキー" , "reading" ,
            "books" , "novel" , "女優" , "nails" , "セブン" , "ファミマ" , "LINE" , "クーポン" , "バイト" ,
            "リリース" , "LINEスタンプ" , "うっせぇわ" , "お酒" , "中華" , "グルメ" , "外食" , "おつまみ" ,
            "ホスト" , "筋トレ" , "ワイン" , "啤酒" , "零食" , "薯片" , "美味しい" , "コーデ" , "beauty" ,
            "自撮り" , "helicopter" , "calligraphy" , "ceramic" , "museum" , "dinosaurs" , "checkers" ,
            "crossword" , "pool" , "swimming" , "snooker" , "darts" , "airsoft" , "サバイバルゲーム" , 
            "science" , "biology" , "chemistry" , "physics" , "massage" , "fimmaking" , "fishing" , "salmon" ,
            "sashimi" , "刺身" ,
            
            "animals", "animal", "birds", "squirrel", "cow", "tiger",
            "cats", "breeds", "dogs", "owls", "parrot", "lions", "dogsoftwitter",
            "catsoftwitter", "husky", "goldenretriver", "persian", "うさぎ" , "鳥" , "japanese" , 
            "ペット" , "pet" , "english" , "英語" , "園芸" , "お笑い" , "jigsaw" , "puzzles" , 
            "skating" , "karate" , "空手" , "相撲" , "sumo" , "刀" , "手品" , "映画鑑賞" , "メイク" ,
            "maze" , "talent" , "Drake" , "TheWeeknd" , "EdSheeran" , "JustinBieber" , "PinkFloyd" , 
            "Queen" , "RoyalFamily" , "コロナ禍" ,
            
            "travel", "Vancouver", "Canada", "USA", "Oregon", "Seattle", "Toronto",
            "California", "Cali", "Europe", "France", "UK", "NewYork", "Florida",
            "Hawaii", "Japan", "Tokyo", "Asia", "China", "SouthKorea", "Korea",
            "Paris", "London", "NYC", "Shanghai", "beijing", "chinese", "backpacking",
            "Australia", "MiddleEast", "Dubai", "Desert", "outdoor", "taipei" , "taiwan" , "turkey" ,
            "England" , "Ireland" , "Brazil" , "ComeToBrazil" , "新宿" , "Africa" , "Antartica" , "NorthPole" ,
            "お守り" , "クッキー" , "お正月" , "京都" , "渋谷" , "神戸" , "九州" , "广州" , "上海" , "北京" , 
            "西安" , "天津" , "青岛" , "深圳" , "香港" , "澳门" ,

            "art", "WIP", "fanart", "wallpaper", "paintings", "digitalart", "1970s",
            "1980s", "1990s", "70s", "80s", "90s", "beards", "ww3" , "ww1" , "okinawa" , "沖縄" , "北海道" , 
            "荒野行動" , "prank" , "swatch" , "ww2" , "history" , "味噌" , "王者荣耀" , "博物館" , "ディズニー" ,
            "日産" , "三菱" , "TOYOTA" , "GTR" , "R32" , "スカイライン" , "旧車" , "フェラーリ" , "マセラティ" , 
            "BMW" , "ベンツ " , "Mechanic" , "German" ,
            
            "tiktok", "memes", "selfie", "swag", "hypebeast",
            "clout", "model", "party", "follow", "ootd", "complexcon", "dance","unboxing" , "youtuber" , 
            "fashion" , "makeup" , "歌ってみた" , "コスプレ" , "レクサス" ,                            
            
            "gym", "sports", "blog", "bench", "supplements", "workout", "biceps",
            "legday", "squats", "fitness", "bodybuilding", "basketball", "soccer", 
            "badminton", "volleyball", "golf", "NBA", "skiing", "crosscountry", "trackandfield",
            "gymnastics", "olympics", "car", "ferrari", "lambo", "motorcycles", "yamaha", "toyota",
            "benz", "bmw", "rollsroyce", "watches", "rolex", "omega", "patek", "patekphilippe",
            "ford", "truck", "landrover", "offroading", "wedding", "dress", "uniform","カレー" , "牛丼" ,
            "すき焼き" , "みかん" , "限定" , "手作り" , "編み物" , "読書" , "朝活" , "本" , "料理" , "gardening" ,
            "knitting" , "折り紙" , "運動" , "ゲーム" , "書道" , "バスケ" , "BAPE" , "サッカー" , "高級車" ,
            "雰囲気" , "Toyota86" , "スープラ" , "スプラ" ,
            
            "food", "vegan", "plantbased", "Dessert", "bubbletea", "cake",
            "coffee", "cola", "candy", "chocolate", "pizza", "noodles",
            "ramen", "pasta", "sandwich", "donuts", "chicken", "foodie",
            "icecream", "foodporn", "bbq", "brisket", "friedchicken", "eggs",
            "rice", "sushi", "tacos", "burritos", "farm", "beer", "wine", 
            "liquor", "baking", "dinner","マリトッツォ" , "ショートケーキ" , "ケーキ" , "蛋糕" , "美食" ,
            "アイス" , "冰激凌" , "草莓" , "拉面" , "雪" , "礼物" , "プレゼント" , "tea" , "お茶" , "ラーメン" , 
            "お寿司" , "デート" , "カップル" , "出会い系" , "meditation" , "絶対領域" , "おもちゃ" , "フィギュア" ,
            "アルパカ" , "alpaca" , "ゆるキャラ" , "美容" ,
            
            "life", "love", "family", "cute", "news", "psychedelic", "tattoo", "lifestyle","BreakingNews" ,
            "Earthquake" , "地震" , "鲜花" , "神社" , "初もうで" , "おみくじ" ,                             
            
            "videogame", "dota2", "leagueoflegends", "razer", "games", "pokemon", "valorant",
            "FPS", "apex", "logitech", "tarkov", "genshinimpact", "csgo", "fifa", "gta", "minecraft",
            "rust", "cod", "TFT", "chess", "xbox", "ps5", "ps4", "ps3",                
            
            "coding", "python", "javascript", "programming", "ruby", "webdev", "datascience", "machinelearning",
            "ai", "deeplearning", "neuralnetwork", "datavisualization", "github", "java", "html", "php", "linux",
            "ubuntu", "macOS", "windows11", "jewelry" , "pilates" , "philosophy" , "コミュニケーション" , "休日" , 
            "楽しい" , "ギャグ" , "漫才" , "パソコン" , "シェアハウス" , "赤ちゃん" , "イケメン" ,                         
            
            "music", "rock", "pop", "guitar", "orchestra", "hiphop", "rap", "spotify", "podcast", "kanye", "yeezy",
            "beatles", "frankocean", "jcole", "kendrick", "tylerthecreator", "kpop", "bts", "piano", "jazz",
            "Soul", "blues", "saxophone", "electronic", "edm", "heavymetal", "metal","ピアノ" , "钢琴" , "釣り" , 
            
            "mood", "happy", "sad", "angry", "wtf", "depression", "depressed", 
            "confused", "grateful","うつ病 " ,"コミュ障 " ,"メンタル" , "オタク" , "陰キャ" , "陽キャ" , "アキバ" , 
            
            "business", "localbusiness", "church", "religion", "jesus", "chirst", "tbt", "wellness", "mentalhealth",
            "smallbusiness" , "暴走族" ,          
            "哲学" , "彼女" , "彼氏" , "Amazon" , "人間関係" , "村上春樹" , "BookTwitter" , "BestSellers" ,              
            
            "school", "zoom", "onlineschool", "inperson", "campus", "COVID19", "vaccine", "pfizer", "moderna", "pandemic",
            "earthquake", "tsunami", "volcano", "explosion",                        
            
            "work", "workfromhome", "WFH","にじさんじ" , "radio" , "goodreads" , "映画" , "読了" , "コーヒー" ,                     
            
            "anime", "vtuber", "gundam", "cosplay", "bokunohero", "onepiece", "bleach", "dragonmaid", "drstone", "shounen", 
            "attackontitan", "aot", "evangelion", "MHA", "JJK", "jujutsukaisen", "manga", "persona", "joker", "doodle", 
            "sketch", "luffy", "zoro", "nami", "strawhats", "twitch", "emotes", "streamers", "demonslayer", "KNY", "jjba",
            "stoneocean", "naruto", "blackclover", "hunterxhunter", "haikyuu", "tokyorevengers","ワンピース" , "ジャンプ" , "漫画" , 
            "マンガ" , "ジョジョ" , "鬼滅の刃" , "イラスト" , "絵" , "野球" , "プロ野球" , "阪神" , "ローソン" ,
            "コラボ" , "禰豆子" , "五条" , "呪術廻戦" , "luxury" , "mrbeast" , "dudeperfect" , "trickshot" , 
            "dream" , "ArianaGrande" , "MAGA" , "healthcare" , "republican" , "democrat" , "JCole" ,
            
            "netflix", "starwars", "movies", "marvel", "superheroes", "spiderman", "ironman" , "harrypotter", "avengers", "thanos",
            "disney" , "starbucks" , "mcdonalds" , "マック" , "restaurant" , "クリスマス" , "イルミネーション" , "着物" , 
            "投資" , "面白い" ,
            
            "holiday", "NewYears", "Christmas", "Thanksgiving", "BlackFriday", "Easter", "ChristmasEve", "Canadaday", "independenceday",
            "スマブラ" , "smashbros" , "idolmaster" , "lovelive" , "3dprinting" , "drama" , "DIY" , "股票" , "株" , 
            "carbonfiber" , "diamond" ,"lego" , "magic" , "robot" , "diving" , "acting" , "pewdiepie" , "markiplier" , "サンドイッチ" , 
            "天ぷら" , "唐揚げ" , "森林" , "ギャル" ,
            
            "technology", "iphone", "iphone3gs", "iphone4", "iphone5", "iphone6", "iphone7", "iphone8", "iphoneX", "iphone11",
            "iphone12", "iphone13", "newiphone", "mac", "macbook", "applesilicon", "ipad", "pixel6", "applewatch", "Oculus",
            "NFTs", "NFT", "Meta", "Metaverse", "crypto", "bitcoin", "VR","宇宙" , "航空" , "愛" , "フリー素材" , "天文" , "望遠鏡" ,
            "漢字" , "space" , "mars" , "ぬいぐるみ" , "旅行" , "海外旅行" ,
            "恐竜" , "地球" , "月" , "怪物" , "モンスター" , "solana" , "ethereum" , "dogecoin" , "elonmusk" , 
            "google" , "facebook" , "instagram" , "twitter" , "snapchat" , "nike" ,"adidas" , "dunks" , "reebok" ,
            "jordans" , "居酒屋" , "残業" , "お菓子" , "おしゃれ" , "ホロライブ" , "ジブリ" , "誕生日" , "ドッキリ" ,
            "ホラー" , "ニュース" , "東海オンエア" , "加藤純一" , "ヒカル" , "ヒカキン" , "セイキン" , 
            "はじめしゃちょ" , "はじめしゃちょー" , "コムドット" , "スカイピース" , "ひろゆき" , "ラブライブ" , "アイドル"
            ]
            

#subreddits
SUBREDDITS = ['100yearsago', '1200isplenty', '2007scape', '2meirl4meirl', '3amjokes', '3Dprinting', '3DS', '4chan', '60fpsporn', 'AbandonedPorn',
              'ABraThatFits', 'AccidentalComedy', 'AccidentalRenaissance', 'ActLikeYouBelong',
              'ADHD', 'AdPorn', 'AdrenalinePorn', 'adventuretime', 'Advice', 'AdviceAnimals', 'AlienBlue', 'Allsvenskan', 'alternativeart', 'altgonewild', 'AMA', 
              'AmazonTopRated', 'AmericanHorrorStory', 'amiugly', 'Anarchism', 'Android', 'androidapps', 'androiddev', 'AndroidGaming', 'androidthemes', 'AnimalCrossing',
              'AnimalPorn', 'AnimalsBeingBros', 'AnimalsBeingDerps', 'AnimalsBeingJerks', 'AnimalTextGifs', 'anime', 'anime_irl', 'announcements', 'ANormalDayInRussia', 'answers', 'AntiJokes',
              'Anxiety', 'apocalympics2016', 'AppHookup', 'apple', 'Aquariums', 'ArcherFX', 'architecture', 'ArchitecturePorn', 'arduino', 'arresteddevelopment', 'arrow', 'Art', 'ArtefactPorn',
              'ArtisanVideos', 'ArtPorn', 'AskCulinary', 'AskEngineers', 'AskHistorians', 'AskMen', 'AskReddit', 'askscience', 'AskScienceFiction', 'AskSocialScience', 'AskWomen', 'asmr', 'asoiaf',
              'assassinscreed', 'Astronomy', 'astrophotography', 'atheism', 'audioengineering', 'audiophile', 'Austin', 'australia', 'Autos', 'aviation', 'awesome', 'aww', 'Awwducational', 'awwnime',
              'awwwtf', 'babyelephantgifs', 'backpacking', 'baconit', 'baconreader', 'Bad_Cop_No_Donut', 'badhistory', 'badtattoos', 'Baking', 'bannedfromclubpenguin', 'baseball', 'batman', 'Battlefield',
              'battlefield_4', 'battlefield_one', 'battlestations', 'bdsm', 'BDSMcommunity', 'BeAmazed', 'beards', 'beer', 'beermoney', 'BeforeNAfterAdoption', 'behindthegifs', 'bertstrips', 'bestof',
              'bestofnetflix', 'BestOfStreamingVideo', 'beta', 'betterCallSaul', 'BetterEveryLoop', 'bicycling', 'bidenbro', 'BikiniBottomTwitter', 'bikinis', 'bimbofetish', 'bindingofisaac', 'biology',
              'birdswitharms', 'bitchimabus', 'Bitcoin', 'bjj', 'blackmirror', 'blackops3', 'blackpeoplegifs', 'BlackPeopleTwitter', 'Blep', 'blog', 'bloodborne', 'Blowjobs', 'blunderyears', 'boardgames',
              'BobsBurgers', 'bodybuilding', 'bodyperfection', 'bodyweightfitness', 'BoJackHorseman', 'BollywoodRealism', 'BonerMaterial', 'books', 'booksuggestions', 'Borderlands', 'BorednIgnored', 'boston',
              'brasil', 'Breadit', 'breakingbad', 'BreastEnvy', 'breathinginformation', 'britishproblems', 'Buddhism', 'budgetfood', 'buildapc', 'buildapcsales', 'Bundesliga',
              'burstingout', 'business', 'BustyPetite', 'buttplug', 'BuyItForLife', 'C25K', 'cableporn', 'calvinandhobbes', 'camping', 'CampingandHiking','canada', 'CandidFashionPolice',
              'carporn', 'cars', 'CasualConversation', 'casualiama', 'CatastrophicFailure', 'catpictures', 'drones',
              'catpranks', 'cats', 'CatsStandingUp', 'Celebs', 'CFB', 'CGPGrey', 'changemyview', 'ChangingRooms', 'Cheap_Meals', 'chemicalreactiongifs', 'chemistry', 'chess', 'chicago', 'childfree',
              'ChildrenFallingOver', 'Christianity', 'Chromecast', 'chubby', 'churning', 'Cinemagraphs', 'circlejerk', 'CitiesSkylines', 'CityPorn', 'civ', 'ClashOfClans', 'ClashRoyale', 'classic4chan',
              'classicalmusic', 'cleavage', 'climbing', 'coding', 'CODZombies', 'Coffee', 'cogsci', 'college', 'CollegeAmateurs', 'CollegeBasketball', 'ColorizedHistory',
              'CombatFootage', 'combinedgifs', 'comicbooks', 'comics', 'community', 'CompetitiveHS', 'Competitiveoverwatch', 'compsci', 'confession', 'ConfusedBoners', 'Conservative', 'conspiracy',
              'conspiratard', 'ContagiousLaughter', 'Cooking', 'coolguides', 'cordcutters', 'corgi', 'CorporateFacepalm', 'cosplay', 'cosplaygirls', 'CozyPlaces', 'crafts', 'CrappyDesign',
              'crappyoffbrands', 'CrazyIdeas', 'creampies', 'creepy', 'creepypasta', 'creepyPMs', 'cringe',
              'CringeAnarchy', 'cringepics', 'CrusaderKings', 'cscareerquestions', 'curvy', 'Cyberpunk', 'Cynicalbrit', 'daddit', 'dadjokes', 'DadReflexes', 'dailyprogrammer',
              'Damnthatsinteresting', 'dankchristianmemes', 'dankmemes', 'DarkAngels', 'DarkNetMarkets', 'darksouls', 'DarkSouls2', 'darksouls3', 'dataisbeautiful', 'datgap', 'dating_advice', 'dayz', 'dbz',
              'DCcomics', 'de', 'de_IAmA', 'DecidingToBeBetter', 'DeepIntoYouTube', 'deepthroat', 'delusionalartists', 'Demotivational', 'Denmark', 'depression', 'DepthHub', 'Design', 'DesignPorn', 'DesirePath',
              'DestinyTheGame', 'DestructionPorn', 'Diablo', 'diablo3', 'DirtyGaming', 'dirtykikpals', 'dirtypenpals', 'dirtyr4r', 'dirtysmall', 'DirtySnapchat', 'disney', 'distension', 'DiWHY', 'DIY', 'DnD', 'doctorwho',
              'Documentaries', 'DoesAnybodyElse', 'dogecoin', 'dogpictures', 'dogs', 'Dogtraining', 'DotA2', 'downblouse', 'dragonage', 'drawing', 'Drugs', 'drunk', 'DrunkOrAKid', 'dubstep', 'DunderMifflin', 'dwarffortress',
              'EarthPorn', 'EatCheapAndHealthy', 'eatsandwiches', 'Economics', 'economy', 'EDC', 'EDM', 'edmproduction', 'education', 'educationalgifs', 'eFreebies', 'elderscrollsonline', 'eldertrees',
              'electronic_cigarette', 'electronicmusic', 'electronics',
              'EliteDangerous', 'EmmaWatson', 'EmpireDidNothingWrong', 'energy', 'engineering', 'EngineeringPorn', 'EngineeringStudents', 'Enhancement', 'EnoughTrumpSpam', 'entertainment', 'Entrepreneur',
              'environment', 'eu4', 'europe', 'Eve', 'everymanshouldknow', 'EverythingScience', 'evilbuildings', 'excel', 'ExpectationVsReality', 'explainlikeIAmA', 'ExplainLikeImCalvin', 'explainlikeimfive', 'ExposurePorn', 'Eyebleach',
              'facebookwins', 'facedownassup', 'facepalm', 'facesitting', 'Fallout', 'FancyFollicles', 'Fantasy', 'fantasyfootball', 'FanTheories', 'fashion', 'fatlogic', 'fatpeoplehate', 'fatpeoplestories', 'FellowKids',
              'femalefashionadvice', 'femalepov', 'Feminism', 'FestivalSluts', 'fffffffuuuuuuuuuuuu', 'ffxiv', 'FIFA', 'FifthWorldPics', 'fifthworldproblems', 'FiftyFifty', 'Filmmakers', 'FinalFantasy', 'finance', 'financialindependence',
              'findareddit', 'fireemblem', 'firefly', 'Fireteams', 'firstworldanarchists', 'firstworldproblems', 'Fishing', 'fitgirls', 'fitmeals', 'Fitness', 'FlashingGirls', 'FlashTV',
              'flexibility', 'Flipping', 'FloridaMan', 'fo4', 'food',
              'Foodforthought', 'foodhacks', 'FoodPorn', 'forcedorgasms', 'ForeverAlone', 'forhire', 'formula1', 'forwardsfromgrandma', 'france', 'freebies', 'FreeEBOOKS', 'FreeGamesOnSteam', 'freeuse', 'friendsafari',
              'Frisson', 'Frugal', 'frugalmalefashion', 'Fullmoviesonvimeo', 'fullmoviesonyoutube', 'funhaus', 'funny', 'funsized',
              'futbol', 'futurama', 'futurebeats', 'futureporn', 'Futurology', 'gadgets', 'gainit', 'gallifrey', 'GameDeals', 'gamedev', 'gamegrumps', 'gamemusic', 'gameofthrones', 'GamePhysics',
              'gamernews', 'Games', 'gaming', 'gardening', 'gaybros', 'gaymers', 'geek', 'gentlemanboners', 'getdisciplined', 'GetMotivated', 'gettingherselfoff', 'ginger', 'glitch_art',
              'Glitch_in_the_Matrix', 'GlobalOffensive', 'GlobalOffensiveTrade',
              'golf', 'GoneMild', 'google', 'gopro', 'Gore', 'Graffiti', 'GrandTheftAutoV', 'graphic_design', 'GreenDawn', 'greentext', 'grilledcheese', 'grool', 'gtaonline', 'GTAV', 'Guildwars2',
              'Guitar', 'guitarlessons', 'Gunners', 'GunPorn', 'guns', 'h3h3productions', 'hacking', 'HailCorporate', 'halo', 'happy', 'happycrowds', 'hardbodies', 'hardcoreaww', 'hardware',
              'harrypotter', 'headphones', 'Health', 'hearthstone', 'Heavymind', 'HeavySeas', 'heroesofthestorm', 'HighQualityGifs', 'hiking',
              'HillaryForPrison', 'HIMYM', 'hiphopheads', 'HistoricalWhatIf', 'history', 'HistoryPorn', 'hitmanimals', 'hockey', 'holdmybeaker', 'holdmybeer', 'holdmyfries', 'holdmyjuicebox',
              'holdthemoan', 'Homebrewing', 'HomeImprovement', 'homelab', 'homestead', 'horror', 'Hotchickswithtattoos', 'HouseOfCards', 'howto', 'HowToHack', 'howtonotgiveafuck', 'HumanPorn',
              'HumansBeingBros', 'humor', 'IAmA', 'iamverybadass', 'iamverysmart', 'IASIP', 'IdiotsFightingThings', 'IDontWorkHereLady', 'ifyoulikeblank', 'illusionporn', 'im14andthisisdeep',
              'ImaginaryLandscapes', 'ImaginaryLeviathans', 'ImaginaryMonsters', 'ImaginaryTechnology', 'ImGoingToHellForThis', 'incest', 'india', 'IndianBabes', 'indianpeoplefacebook', 'IndieGaming',
              'indieheads', 'Infographics', 'InfrastructurePorn', 'Innie', 'instant_regret', 'interestingasfuck', 'InteriorDesign', 'InternetIsBeautiful', 'intresseklubben', 'introvert', 'investing',
              'iphone', 'ireland', 'italy', 'itookapicture', 'IWantOut', 'iWantToFuckHer', 'IWantToLearn', 'jailbreak', 'japan', 'JapaneseGameShows', 'java', 'javascript', 'Jazz', 'jesuschristreddit',
              'jilling', 'jobs', 'JoeRogan', 'Jokes', 'juicyasians', 'Justfuckmyshitup', 'JusticePorn', 'JusticeServed', 'justneckbeardthings', 'JUSTNOMIL', 'Justrolledintotheshop', 'Kanye',
              'KarmaConspiracy', 'KenM', 'KerbalSpaceProgram', 'keto', 'ketorecipes', 'knitting', 'knives', 'KotakuInAction', 'kpop', 'LadyBoners', 'ladybonersgw', 'languagelearning', 'lastimages', 'LateStageCapitalism', 'latinas', 'law',
              'leagueoflegends', 'LearnJapanese', 'learnprogramming', 'learnpython', 'LearnUselessTalents', 'lectures', 'legaladvice', 'lego', 'legs', 'lesbians', 'LetsNotMeet',
              'lewronggeneration', 'lgbt', 'Libertarian', 'lifehacks', 'lifeofnorman', 'LifeProTips', 'likeus', 'lingerie', 'linguistics', 'linux', 'LipsThatGrip', 'listentothis', 'literature', 'LivestreamFail', 'lockpicking', 'lolcats', 'LoLeventVoDs',
              'london', 'longboarding', 'LosAngeles', 'loseit', 'lotr', 'LSD', 'LucidDreaming', 'mac', 'MachineLearning', 'MachinePorn', 'MadeMeSmile', 'madlads', 'magicTCG', 'MakeupAddiction', 'MakingaMurderer', 'malefashion', 'malefashionadvice',
              'malehairadvice', 'malelifestyle', 'malelivingspace', 'mallninjashit', 'manga', 'MapPorn', 'Marijuana', 'marijuanaenthusiasts', 'marketing', 'Marvel', 'marvelstudios', 'mashups', 'masseffect', 'math', 'me_irl', 'MealPrepSunday', 'MeanJokes',
              'mechanical_gifs', 'MechanicalKeyboards', 'medicine', 'Meditation', 'meirl', 'MemeEconomy', 'memes', 'MensRights', 'MEOW_IRL', 'Metal', 'metalgearsolid', 'mexico', 'michaelbaygifs', 'microgrowery', 'mildlyinfuriating', 'mildlyinteresting', 'milf', 'Military',
              'MilitaryPorn', 'millionairemakers', 'Minecraft', 'minimalism', 'misleadingthumbnails', 'MLS', 'MMA', 'modnews', 'MonsterHunter', 'montageparodies', 'MorbidReality', 'motorcycles', 'MoviePosterPorn', 'movies', 'Moviesinthemaking', 'MrRobot',
              'MTB', 'MURICA', 'MuseumOfReddit', 'Music', 'musictheory', 'mylittlepony', 'MyPeopleNeedMe', 'Naruto', 'nasa', 'NatureIsFuckingLit', 'natureismetal', 'nba', 'nbastreams', 'netflix', 'NetflixBestOf', 'netsec', 'networking', 'NeutralPolitics',
              'nevertellmetheodds', 'newreddits', 'news', 'newzealand', 'nextdoorasians', 'nfl', 'nflstreams', 'nhl', 'NHLStreams', 'niceguys', 'nintendo', 'NintendoSwitch', 'nocontext', 'NoFap', 'NoMansSkyTheGame', 'nononono', 'nonononoyes', 'Nootropics', 'norge',
              'nosleep', 'nostalgia', 'NoStupidQuestions', 'notinteresting', 'NotMyJob', 'nottheonion', 'NotTimAndEric', 'nutrition', 'nyc', 'O_Faces', 'ObscureMedia', 'oculus', 'oddlysatisfying', 'ofcoursethatsathing', 'offbeat', 'Offensive_Wallpapers',
              'offmychest', 'Ohlympics', 'OkCupid', 'oldpeoplefacebook', 'OldSchoolCool', 'olympics', 'OnePiece', 'oneplus', 'OnePunchMan', 'onetruegod', 'onions', 'OopsDidntMeanTo', 'OSHA', 'OutOfTheLoop', 'outrun', 'outside', 'Overwatch', 'OverwatchUniversity',
              'Paleo', 'PandR', 'Paranormal', 'Pareidolia', 'Parenting', 'pathofexile', 'patientgamers', 'Patriots', 'pcgaming', 'pcmasterrace', 'PenmanshipPorn', 'PeopleFuckingDying', 'Perfectfit', 'perfectloops', 'PerfectTiming', 'personalfinance', 'pettyrevenge',
              'Philippines', 'philosophy', 'photography', 'photoshopbattles', 'Physics', 'piano', 'pics', 'Piracy', 'PixelArt', 'Pizza', 'playrust', 'Poetry', 'pokemon', 'pokemongo', 'pokemontrades', 'poker', 'pokies', 'polandball', 'Political_Revolution',
              'PoliticalDiscussion', 'PoliticalHumor', 'politics', 'Polska', 'popping', 'Portland', 'powerwashingporn', 'Prematurecelebration', 'privacy', 'productivity', 'ProgrammerHumor', 'programming', 'progresspics', 'PropagandaPosters',
              'ProRevenge', 'PS3', 'PS4', 'PS4Deals', 'psychology', 'Psychonaut', 'PublicFlashing', 'PublicFreakout', 'Punny', 'pussypassdenied', 'Pyongyang', 'Python', 'quityourbullshit', 'quiver', 'quotes', 'QuotesPorn', 'r4r', 'rage', 'Rainbow6',
              'Rainmeter', 'raisedbynarcissists', 'ramen', 'RandomActsOfBlowJob', 'RandomActsOfGaming', 'randomsexiness', 'rarepuppers', 'raspberry_pi', 'Rateme', 'reactiongifs', 'RealEstate',
              'reallifedoodles', 'recipes', 'reddevils', 'redditgetsdrawn', 'RedditLaqueristas', 'redditsync', 'redheads',
              'relationship_advice', 'relationships', 'RelayForReddit', 'retiredgif', 'RetroFuturism', 'ReverseEngineering', 'rickandmorty', 'Roadcam', 'RoastMe', 'RocketLeague', 'RoomPorn', 'roosterteeth', 'rpg', 'rule34', 'rule34_comics', 'runescape', 'running',
              'rupaulsdragrace', 'sadcringe', 'SandersForPresident', 'sanfrancisco', 'savedyouaclick', 'science', 'scifi', 'Scotch', 'ScottishPeopleTwitter', 'Screenwriting', 'Seattle', 'secretsanta', 'seduction', 'seinfeld', 'self', 'selfimprovement', 'serialkillers',
              'serialpodcast', 'sewing', 'SheLikesItRough', 'Sherlock', 'ShitRedditSays',
              'Shitty_Car_Mods', 'shittyadvice', 'shittyaskscience', 'shittyfoodporn', 'shittykickstarters',
              'ShittyLifeProTips', 'shittyreactiongifs', 'shittyrobots', 'shorthairchicks',
              'shortscarystories', 'Showerthoughts', 'shutupandtakemymoney', 'SiliconValleyHBO',
              'simpleliving', 'simps', 'Simulated', 'singapore', 'skateboarding',
              'skeptic', 'SketchDaily', 'skiing', 'SkincareAddiction', 'SkyPorn', 'skyrim', 'skyrimmods',
              'sloths', 'slowcooking', 'smallbusiness', 'smashbros', 'Smite',
              'Sneakers', 'Sneks', 'snowboarding', 'soccer', 'soccerstreams', 'SocialEngineering', 'socialism',
              'socialskills', 'softwaregore', 'solotravel', 'somethingimade', 'southpark', 'space', 'spaceporn',
              'spacex', 'speedrun', 'spop', 'sports', 'sportsarefun', 'spotify', 'SquaredCircle', 
              'Stacked', 'StandUpComedy', 'standupshots',
              'starbound', 'starcitizen', 'starcraft', 'StardewValley', 'starterpacks', 'StartledCats', 'startrek',
              'startups', 'StarWars', 'StarWarsBattlefront', 'Steam', 'steamdeals', 'stevenuniverse',
              'stockings', 'stocks', 'StonerEngineering', 'stopdrinking', 'StoppedWorking', 'StraightGirlsPlaying',
              'StrangerThings', 'StreetFights', 'streetwear', 'StruggleFucking', 'subaru', 'SubredditDrama',
              'subredditoftheday', 'SubredditSimulator', 'suctiondildos', 'suicidegirls', 'SuicideWatch',
              'summonerschool', 'Suomi', 'Supernatural', 'SuperShibe', 'Survival', 'svenskpolitik',
              'SWARJE', 'SweatyPalms', 'sweden', 'swedishproblems', 'swoleacceptance', 'swtor', 'sysadmin',
              'TalesFromRetail', 'talesfromtechsupport', 'TalesFromYourServer', 'tall', 'tattoo', 'tattoos',
              'tea', 'tech', 'technology', 'techsupport', 'techsupportgore', 'techsupportmacgyver',
              'teenagers', 'television', 'Terraria', 'terriblefacebookmemes', 'teslamotors', 'tf2', 
              'Tgirls', 'thalassophobia', 'ThanksObama', 'thatHappened', 'The_Donald', 'TheBestOfAmazon',
              'thebutton', 'TheDepthsBelow', 'thedivision', 'TheFappening', 'TheGirlSurvivalGuide', 'thegrandtour',
              'TheLastAirbender', 'thenetherlands', 'theocho', 'TheoryOfReddit', 'TheRedPill', 'therewasanattempt',
              'TheSilphRoad', 'TheSimpsons', 'thesims', 'Thetruthishere', 'thewalkingdead', 'TheWayWeWere',
              'theydidthemath', 'ThingsCutInHalfPorn', 'thingsforants', 'thisismylifenow', 'ThreadKillers',
              'ThriftStoreHauls', 'Tinder', 'TinyHouses', 'tipofmytongue', 'titanfall', 'tldr', 'todayilearned',
              'toosoon', 'TopGear', 'toronto', 'torrents', 'totallynotrobots', 'totalwar', 'trackers',
              'trailerparkboys', 'trashy', 'trashyboners', 'travel', 'trees', 'trippinthroughtime',
              'TrollXChromosomes', 'TrollYChromosome', 'TrueAskReddit', 'TrueAtheism', 'TrueDetective',
              'TrueFilm', 'truegaming', 'TrueReddit', 'tumblr', 'TumblrInAction', 'Twitch', 'TwoXChromosomes',
              'typography', 'Ubuntu', 'ufc', 'UFOs', 'ukpolitics', 'Unashamed', 'UNBGBBIIVCHIDCTIICBG', 'uncensorednews',
              'undelete', 'Undertale', 'Unexpected', 'unexpectedjihad', 'UnexpectedThugLife', 'unitedkingdom',
              'Unity3D', 'UniversityofReddit', 'unixporn', 'UnresolvedMysteries', 'UpliftingNews', 'Upskirt',
              'urbanexploration', 'vancouver', 'vandwellers',
              'vaporents', 'Vaporwave', 'vegan', 'vegetarian', 'vexillology', 'videos', 'VillagePorn',
              'vinyl', 'vita', 'Vive', 'VolleyballGirls', 'voluptuous', 'wallpaper', 'wallpapers',
              'wallstreetbets', 'Warframe', 'WastedGifs', 'Watches', 'WatchItForThePlot', 'watchpeopledie',
              'waterporn', 'WeAreTheMusicMakers', 'WeatherGifs', 'web_design', 'webcomics', 'webdev', 'WebGames',
              'weightroom', 'Wellthatsucks', 'westworld', 'Whatcouldgowrong', 'whatisthisthing', 'WhatsInThisThing',
              'wheredidthesodago', 'whitepeoplegifs', 'wholesomememes', 'whowouldwin', 'wicked_edge', 'wifesharing',
              'wiiu', 'WikiLeaks', 'wikipedia', 'windows', 'Windows10', 'witcher', 'woahdude', 'WomenOfColor',
              'woodworking', 'worldbuilding', 'worldcup', 'worldnews', 'worldpolitics', 'WouldYouFuckMyWife',
              'WouldYouRather', 'wow', 'wowthissubexists', 'writing', 'WritingPrompts', 'WTF', 'WtSSTaDaMiT',
              'xboxone', 'xkcd', 'xxfitness', 'yoga', 'YogaPants', 'Yogscast', 'youdontsurf', 'YouSeeComrade',
              'youseeingthisshit', 'YouShouldKnow', 'youtube', 'youtubehaiku', 'zelda', 'ZenHabits', 'zombies']

#sensitive hashtags to exclude while crawling
SENSITIVE_HASHTAGS = [
                      "cock", "penis", "sex", "ass", "pussy", "fetish", "kink",
                      "dick", "anal", "tits", "cuckold", "orgasm", "gangbang", "job",
                      "masturbation", "milf", "porn", "licking", "squirt", "18+", 
                      "threesome", "rule34", "NSFW", "onlyfans", "leak", "egirl", "cum", 
                      "backshot", "pawg", "bbc", "blacked", "horny", "bigdick", "gorillagrip", 
                      "bigtits", "bitch", "tease", "naked", "sexy", "nude", "slut", "furry", 
                      "gay", "bulge", "femdom", "findom", "hentai", "xxx", "blowjob", "gayporn", "lesbian",
                      "hairy", "daddy", "骚比" , "大奶" , "メンエス" , "エッチ" , "エロ動画" , "風俗" , "デリヘル" ,
                       "エステ" , "dmm"
                    ]
