import React, {useEffect} from 'react'
import {Row, Col, Carousel} from 'antd'
import {
  EmailShareButton, EmailIcon
} from "react-share"
import { Link } from 'react-router-dom'

function onChange(a, b, c) {
  console.log(a, b, c);
}


export default() => {
    useEffect(() => {window.scrollTo(0, 0);});
    useEffect(() => {
        document.title = "Meepoer - FAQ";  
      }, []);
    
    const domainname = '3.99.16.231'

    return <div className='faq-container'>
    
    <div className='faq-title'><h1>Frequently Asked Questions</h1></div>
      <Row justify='center' gutter={[88, 24]}>
        <Col md={20} lg={6} style={{textAlign:'left'}} className='table-of-contents'>
          <h3>Cost</h3>
          <div className='question'>
            <a href='#free'>Is Meepoer free to use?</a>
            </div>
          <h3>Privacy</h3>
          <div className='question'>
            <a href='#whocansee'>Who can see my photos?</a>
          </div>
          <div className='question'>
            <a href='#savephoto'>Does Meepoer save my photo?</a>
          </div>
          <h3>Science</h3>
          <div className='question'>
            <a href='#howwork'>How does Meepoer work?</a>
          </div>
          <div className='question'>
            <a href='#nameorigin'>Where did the name Meepoer come from?</a>
          </div>

          </Col>
        <Col md={20} lg={16} style={{textAlign:'left'}} className='answers'>

          <h3 id='free'>Is Meepoer free to use?</h3>
          <p>Yes, Meepoer is free to use for your own pleasure. However we do not own any of the images
            reproduced from the post generation. All rights belong to their respective owners. 
          </p>
          <p>Read our <Link to="/terms">Terms of Use </Link>
             before generating your first post!</p>

          <h3 id='whocansee'>Who can see my posts?</h3>
          <p>The gallery of posts generated from either our <Link to="/text-to-post-db">Text-to-Post </Link>
          or <Link to="/post-to-post">Post-to-Post </Link> features is only for your eyes until you decide 
          to share them with the built-in share buttons.</p>

          <h3 id='savephoto'>Does Meepoer save my photo?</h3>
          <p>No, Meepoer does not save the photo you have uploaded to the <Link to="/post-to-post">Post-to-Post </Link> feature.
          User-uploaded images are temporary stored until the page is closed.</p>
          <p>We will not be able to see
          your uploaded content.</p>
          <p>Individual user accounts for storing the generated posts are still under development.</p>
          <h3 id='howwork'>How does Meepoer work?</h3>
          <p>It all starts with which feature (<Link to="/text-to-post-db">Text-to-Post </Link>
          or <Link to="/post-to-post">Post-to-Post</Link>) you have chose to generate posts with.</p>
          <p>We currently support text to post, image to post, and url to post</p>
          <p>Text to post: Posts will be generated based on your text. You could adjust some of the features of your post by checking out the demo video and configuration on <Link to="/text-to-post-db-result">Text-to-Post </Link></p>
          <p>Image to post: Posts will be generated based on your image. We run your image through our image feature database generated by AI, in order to find the best match.
            Check the feature out at <Link to="/image-to-post-gallery"> Image-to-post </Link></p>  
          <p>URL to post: Posts will be generated based on another social media post link. Check the feature out at <Link to="/url-to-post-gallery">URL-to-post </Link></p>  
          <h3 id='nameorigin'>Where did the name Meepoer come from?</h3>
          <p>The developers are DOTA2 players, the idea of Meepoer came from Meepo, which is a character who summons copies of himself.</p>
          <h3 id='specific'>Have a specific question about Meepoer?</h3>
          <p style={{float:'left'}}>Email us at meepoer@126.com!</p>
          <EmailShareButton url={domainname} subject='I have a question about Meepoer!'
          style={{paddingLeft:"2%", float:'left', zIndex:10000}}>
              <EmailIcon size={30}></EmailIcon>
          </EmailShareButton>
          </Col>
      </Row>
       </div>
}